## Pytorch tensors

In [1]:
import torch
import numpy as np

In [2]:
t = torch.Tensor([[1, 2],[3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# from numpy
numpy_array = np.array([[1, 2], [3, 4]])
t = torch.from_numpy(numpy_array)
t

tensor([[1, 2],
        [3, 4]])

In [4]:
# tensor of 0s
shape = (3, 4)
tensor_zeros_34 = torch.zeros(size=shape) # 3x4
print(f"{tensor_zeros_34=}")

tensor = torch.Tensor([[1, 2], [3, 4]])
tensor_zeros_22 = torch.zeros_like(tensor) # 2x2
print(f"{tensor_zeros_22=}")

tensor_zeros_34=tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_zeros_22=tensor([[0., 0.],
        [0., 0.]])


In [6]:
# tensor of 1s
shape = (3, 4)
tensor_ones_34 = torch.ones(size=shape) # 3x4
print(f"{tensor_ones_34=}")

tensor = torch.Tensor([[1, 2], [3, 4]])
tensor_ones_22 = torch.ones_like(tensor) # 2x2
print(f"{tensor_ones_22=}")

tensor_ones_34=tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor_ones_22=tensor([[1., 1.],
        [1., 1.]])


In [8]:
# random tensors

# 3x4 tensor where each component follows normal distribution with mean 0 and standard deviation 1
tensor_random_normal_1 = torch.randn(size=shape) 
tensor_random_normal_2 = torch.randn_like(tensor) 

print(tensor_random_normal_1)
print(tensor_random_normal_2)

tensor([[-1.2431,  0.8008,  2.2092, -0.9773],
        [ 0.2409, -0.2553, -0.8382,  1.9927],
        [ 0.0478,  1.9949,  0.1539, -1.6333]])
tensor([[ 1.7968, -1.7657],
        [ 0.6264,  0.5306]])


In [9]:
# 3x4 tensor following uniform distribution between 0 and 1
tensor_random_uniform_1 = torch.rand(size=shape)
tensor_random_uniform_2 = torch.rand_like(tensor)

print(tensor_random_uniform_1)
print(tensor_random_uniform_2)

tensor([[0.0438, 0.7438, 0.7416, 0.9187],
        [0.0231, 0.9466, 0.8844, 0.8370],
        [0.2552, 0.1690, 0.8853, 0.6158]])
tensor([[0.4238, 0.1675],
        [0.6845, 0.7957]])


In [10]:
# add
tensor + 5

tensor([[6., 7.],
        [8., 9.]])

In [11]:
# mul
tensor * 2

tensor([[2., 4.],
        [6., 8.]])

In [12]:
t1 = torch.Tensor([[1, 2], [3, 4]])
t2 = torch.Tensor([1, 2])

t1 - t2

tensor([[0., 0.],
        [2., 2.]])

In [13]:
t1 + t2

tensor([[2., 4.],
        [4., 6.]])

In [14]:
t1 * t2

tensor([[1., 4.],
        [3., 8.]])

In [26]:
torch.exp(tensor)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]])

In [27]:
torch.log(tensor)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])

In [28]:
torch.min(tensor)

tensor(1.)

In [29]:
torch.max(tensor)

tensor(4.)

In [30]:
torch.mean(tensor)

tensor(2.5000)

In [31]:
tensor = torch.Tensor([[1, 2], [3, 4], [5, 6]])  # 3x2

mean_row = torch.mean(tensor, dim=0)  # shape = (2,) over 1st dimension (columns)
mean_col = torch.mean(tensor, dim=1)  # shape = (3,) over 2nd dimension (rows)

print(mean_row)
print()
print(mean_col)

tensor([3., 4.])

tensor([1.5000, 3.5000, 5.5000])


In [32]:
# logistic function
l = 1 / (1 + torch.exp(-1 * tensor))
l

tensor([[0.7311, 0.8808],
        [0.9526, 0.9820],
        [0.9933, 0.9975]])

In [33]:
print(type(tensor.mean()))

# converting to python scalar 
mean_item = tensor.mean().item()
print(mean_item,  type(mean_item))

<class 'torch.Tensor'>
3.5 <class 'float'>


In [34]:
tensor.size()

torch.Size([3, 2])

In [35]:
tensor.shape

torch.Size([3, 2])

In [36]:
tensor.view(2, 3) # 2x3

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [37]:
tensor.view(6) 

tensor([1., 2., 3., 4., 5., 6.])

In [38]:
tensor.view(1, 6, 1)

tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.]]])

In [39]:
tensor.view(-1, 3) # (-1, 3) = (2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [41]:
print(tensor) # original
print()
tensor_2 = tensor.view(2, 3)
# view() produces a shallow copy of the tensor (reshaped). 
# so changing any of the elements in the view, 
# will also update the value in the original tensor.
tensor_2[0, 0] = 9

print(tensor_2)
print()
print(tensor)

tensor([[9., 2.],
        [3., 4.],
        [5., 6.]])

tensor([[9., 2., 3.],
        [4., 5., 6.]])

tensor([[9., 2.],
        [3., 4.],
        [5., 6.]])


In [55]:
# concate
t1 = torch.randn(size=(1, 4))
t2 = torch.randn(size=(2, 4))
c = torch.cat(tensors=(t1, t2), dim=0)
print(c)
print(c.shape)

tensor([[ 2.5167,  0.2614, -1.4637, -0.1772],
        [-1.4461, -0.9934,  0.2219, -0.4414],
        [-0.2583,  1.0648,  0.3896,  1.0399]])
torch.Size([3, 4])


In [54]:
t1 = torch.randn(size=(3, 1))
t2 = torch.randn(size=(3, 5))
con = torch.cat(tensors=(t1, t2), dim=1)
print(con)
print()
print(con.shape)

tensor([[-1.4622,  1.6262,  1.0716, -0.2890,  0.2489,  0.5327],
        [ 0.5317,  0.3702, -0.8099,  0.6519, -0.2694, -0.2961],
        [-0.6904, -0.3192,  0.4642, -0.4340, -0.3126, -2.8074]])

torch.Size([3, 6])


In [56]:
t = torch.randn(size=(3, 4))
t

tensor([[-0.0387, -0.0845, -0.8049, -0.0037],
        [-0.1500, -0.0360, -0.2906, -0.0605],
        [-1.4079, -0.6107, -0.8153, -0.9418]])

In [63]:
# get second line
t[1, :] # row

tensor([-0.1500, -0.0360, -0.2906, -0.0605])

In [64]:
# get 2 col
t[:, 1] # col

tensor([-0.0845, -0.0360, -0.6107])

In [65]:
# get 2 and 3 col
t[:, 1:3]

tensor([[-0.0845, -0.8049],
        [-0.0360, -0.2906],
        [-0.6107, -0.8153]])

In [66]:
t[1:2,:]

tensor([[-0.1500, -0.0360, -0.2906, -0.0605]])

In [67]:
t[1:2, 2:3]

tensor([[-0.2906]])